package io.plasmasimulator.conf

enum class Address {
  ETH_NODES_BROADCAST,
  PLASMA_BROADCAST,
  GENESIS_PLASMA_BLOCK,
  PUBLISH_ADDRESS,
  PUSH_ALL_ADDRESSES,
  APPLY_BLOCK,
  RUN_PLASMA_CHAIN,
  SET_PLASMA_CONTRACT_ADDRESS,
  REQUEST_ADDRESS
}
