package io.plasmasimulator.conf

enum class Address {
  ETH_NODES_BROADCAST,
  ISSUE_TRANSACTION,
  RECEIVE_TRANSACTION,
  GENESIS_PLASMA_BLOCK,
  GENESIS_PLASMA_BLOCK_ADDED,
  PUBLISH_BLOCK,
  PUBLISH_TRANSACTION,
  PUBLISH_ADDRESS,
  PUSH_ALL_ADDRESSES,
  APPLY_BLOCK,
  RUN_PLASMA_CHAIN,
  SET_PLASMA_CONTRACT_ADDRESS,
  REQUEST_ADDRESS,
  DEPOSIT_TRANSACTION
}
